RECIPIENT_TYPE_GROUP = "group"
RECIPIENT_TYPE_INDIVIDUAL = "individual"
RECIPIENT_TYPE_DEFAULT = RECIPIENT_TYPE_INDIVIDUAL
MESSAGE_TYPE_TEXT = "text"
MESSAGE_TYPE_AUDIO = "audio"
MESSAGE_TYPE_DOCUMENT = "document"
MESSAGE_TYPE_IMAGE = "image"
MESSAGE_TYPE_HSM = "hsm"
